# travis ymal file for python3 development

language: python

python:
  - 2.7
  - 3.5
  - 3.6 
  
install:
  - pip install -r requirements.txt

script:
  python setup.py install
  poretools squiggle test_data/2016_3_4_3507_1_ch13_read1474_strand.fast5